### ISSUE TITLE
Integrate product stock check

### ISSUE THREAD

**Issue by lkpallarca** [eefborromeo/private-dermatology#39]
Add a checker to prevent user from checking out items if the product does not have a stock anymore.

A user can add items to their cart, but if the product stock becomes depleted while a user has that item in their cart, they should not be able to checkout.

**Comment by lkpallarca** [comment]
@jarayumang I can't seem to replicate the error you encountered last night. Can you try and replicate it again to see what triggers the error?

**Comment by jarayumang** [comment]
I will close this issue as per our talk, the admin should have access to appointment transactions page instead of appointments page.
